### ISSUE TITLE
Проверить ДЗ Авито полностью на JDBC

### ISSUE THREAD

**Issue by AleksandrNagovitsyn** [AleksandrNagovitsyn/AvitoJdbc#1]
https://github.com/AleksandrNagovitsyn/AvitoJdbc/blob/afbd42d1b9d2caa740d06f2b7893952ab6a3700c/src/main/java/ru/itpark/service/RepositoryInMemory.java#L26

Получается здесь мы говорим коллекции "Если у твоих объектов id как у house, удаляй их"?

**Comment by coursar** [comment]
Так точно
