### ISSUE TITLE
Если мы берём InMemory реализацию, разве может она выкидывать SQLException?

### ISSUE THREAD

**Issue by coursar** [AleksandrNagovitsyn/AvitoJdbc#7]
https://github.com/AleksandrNagovitsyn/AvitoJdbc/blob/afbd42d1b9d2caa740d06f2b7893952ab6a3700c/src/main/java/ru/itpark/service/HouseRepository.java#L9-L10

**Comment by AleksandrNagovitsyn** [comment]
Сделано в fixes #4, не знаю как закрыть через коммит и пуш этот ишью

**Comment by coursar** [comment]
Руками закрывайте, раз тогда не закрыли
